DROP DATABASE IF EXISTS bd;
CREATE DATABASE bd;

USE bd;


CREATE TABLE PARTIDA (
        ID INT NOT NULL,
	FECHA VARCHAR (60),
	HORA VARCHAR (60),
	ESTADO VARCHAR(60),
   	DURACION INT,
	GANADOR VARCHAR (60),
        PRIMARY KEY (ID)
)ENGINE=InnoDB;



CREATE TABLE JUGADOR (
    ID INT NOT NULL,
    USERNAME VARCHAR(60),
    PASWORD VARCHAR(60),
    PRIMARY KEY (ID)
)ENGINE=InnoDB;


CREATE TABLE PUNTUACION (
   	ID_P INT NOT NULL,
   	ID_J INT NOT NULL,
	PUNTOS INT,
	FOREING KEY (ID_P) REFERENCES PARTIDA(ID)
	FOREING KEY (ID_J) REFERENCES JUGADOR(ID)
)ENGINE=InnoDB;

INSERT INTO PARTIDA VALUES (1, '4-03-2021', '21:00', 'FINALIZADA', 30, 'DANIEL');
INSERT INTO PARTIDA VALUES (2, '5-03-2021', '21:00', 'EN CURSO', 30, 'PABLO');
INSERT INTO PARTIDA VALUES (3, '4-03-2021', '19:00', 'FINALIZADA', 30, 'JORDI');


INSERT INTO JUGADOR VALUES (1, 'JORDI', 'J0');
INSERT INTO JUGADOR VALUES (2, 'PABLO', 'PA');
INSERT INTO JUGADOR VALUES (3, 'DANIEL', 'DA');
INSERT INTO JUGADOR VALUES (4, 'PEPE', 'PE');



INSERT INTO PUNTUACION VALUES (1, 2, 15);
INSERT INTO PUNTUACION VALUES (2, 2, 10); 
INSERT INTO PUNTUACION VALUES (3, 1, 20);
INSERT INTO PUNTUACION VALUES (2, 3, 11);
INSERT INTO PUNTUACION VALUES (1, 2, 22);
INSERT INTO PUNTUACION VALUES (3, 3, 7);



SELECT PUNTACUION.PUNTOS FROM (PARTIDA, JUGADOR, PUNTUACION)
WHERE JUGADOR.USERNAME = 'JORDI'
AND PUNTUACION.ID_P = PARTIDA.ID
AND PARTIDA.ID =1;












